In [ ]:
import numpy  as np

In [ ]:
s=np.array(0,ndmin=10)
s.ndim
s

array([[[[[[[[[[0]]]]]]]]]])

In [ ]:
print(np.array([1,2,3,4]).ndim)
print(np.array([[1,2,3],[4,5,6]]).ndim)
print(np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]).ndim)

1
2
3


In [ ]:
s=b'gayamsunilkumar'
np.frombuffer(s,dtype='S1',offset=3,count=2)

array([b'a', b'm'], dtype='|S1')

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
a.ndim

2

In [ ]:
for i in np.nditer(a,order='F'):
  print(i)


1
4
2
5
3
6


In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b=[i for i in range(10)]
np.fromiter(b,dtype='int',count=5)

array([0, 1, 2, 3, 4])

In [ ]:
np.zeros([2,3],dtype='float')

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones([1,4])

array([[1., 1., 1., 1.]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.full([2,3],5)

array([[5, 5, 5],
       [5, 5, 5]])

In [ ]:
np.arange(1,100,4,dtype='int')

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65,
       69, 73, 77, 81, 85, 89, 93, 97])

In [ ]:
np.linspace(1,20,3,dtype='float',retstep=True)

(array([ 1. , 10.5, 20. ]), np.float64(9.5))

In [ ]:
np.logspace(1,100,5,base=2)

array([2.00000000e+00, 5.64316032e+07, 1.59226292e+15, 4.49269746e+22,
       1.26765060e+30])

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.shape

(2, 3)

In [ ]:
a.size

6

In [ ]:
b=a.copy()
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b[0][1]=8

In [ ]:
b

array([[1, 8, 3],
       [4, 5, 6]])

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
s=a.view()
s

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
s[0][1]=9
s

array([[1, 9, 3],
       [4, 5, 6]])

In [ ]:
a

array([[1, 9, 3],
       [4, 5, 6]])

In [ ]:
a.sort(axis=0)

In [ ]:
a

array([[1, 3, 6],
       [4, 5, 9]])

In [ ]:
c=np.arange(1,7,).reshape(2,3)
c

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.append(a,c,axis=0)

array([[1, 3, 6],
       [4, 5, 9],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.__version__

'2.0.2'

In [ ]:
import numpy as np

In [ ]:
a=np.arange(1,20,2).reshape(2,5)
b=np.arange(21,40,2).reshape(2,5)

In [ ]:
a

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [ ]:
b

array([[21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39]])

In [ ]:
np.concatenate((a,b),axis=1)

array([[ 1,  3,  5,  7,  9, 21, 23, 25, 27, 29],
       [11, 13, 15, 17, 19, 31, 33, 35, 37, 39]])

In [ ]:
np.hstack((a,b))

array([[ 1,  3,  5,  7,  9, 21, 23, 25, 27, 29],
       [11, 13, 15, 17, 19, 31, 33, 35, 37, 39]])

In [ ]:
np.vstack((a,b))

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39]])

In [ ]:
np.dstack((a,b))

array([[[ 1, 21],
        [ 3, 23],
        [ 5, 25],
        [ 7, 27],
        [ 9, 29]],

       [[11, 31],
        [13, 33],
        [15, 35],
        [17, 37],
        [19, 39]]])

In [ ]:
a=a.flatten()

In [ ]:
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
x=np.split(a,2)
c,d=x
c,d

(array([1, 3, 5, 7, 9]), array([11, 13, 15, 17, 19]))

In [ ]:
np.where(a>15)

(array([8, 9]),)

In [ ]:
np.searchsorted(a,5)

np.int64(2)

In [ ]:
pip install numpy

In [ ]:
import numpy as np

In [ ]:
a=np.array(10)
a

array(10)

In [ ]:
a.ndim

0

In [ ]:
b=np.array([1,2,23,3])
b

array([ 1,  2, 23,  3])

In [ ]:
b.ndim

1

In [ ]:
c=np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
c.ndim

2

In [ ]:
c.shape

(2, 3)

In [ ]:
c.size

6

In [ ]:
c.dtype

dtype('int64')

In [ ]:
type(c)

numpy.ndarray

In [ ]:
d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
d.ndim

3

In [ ]:
e=np.array(10,ndmin=1)
e

array([10])

In [ ]:
np.__version__

'2.0.2'

In [ ]:
e.ndim

1

In [ ]:
b=b'gayamsunilkumar'
b

b'gayamsunilkumar'

In [ ]:
np.frombuffer(b,dtype='S1')

array([b'g', b'a', b'y', b'a', b'm', b's', b'u', b'n', b'i', b'l', b'k',
       b'u', b'm', b'a', b'r'], dtype='|S1')

In [ ]:
np.frombuffer(b,dtype='S1',offset=3)

array([b'a', b'm', b's', b'u', b'n', b'i', b'l', b'k', b'u', b'm', b'a',
       b'r'], dtype='|S1')

In [ ]:
np.frombuffer(b,dtype='S1',offset=3,count=7)

array([b'a', b'm', b's', b'u', b'n', b'i', b'l'], dtype='|S1')

In [ ]:
np.fromiter([1,2,3],dtype='float')

array([1., 2., 3.])

In [ ]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
for i in np.nditer(c):
  print(i)

1
2
3
4
5
6


In [ ]:
import numpy as np

In [ ]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.full([3,4],5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [ ]:
a=np.eye(3)
a.ndim

2

In [ ]:
x=np.arange(1,20,2,dtype='float')
x.size

10

In [ ]:
x=x[:6].reshape(2,3)
x

array([[ 1.,  3.,  5.],
       [ 7.,  9., 11.]])

In [ ]:
for i in np.nditer(x,order="F"):
  print(i)

1.0
7.0
3.0
9.0
5.0
11.0


In [ ]:
np.linspace(1,10,3,retstep=True)

(array([ 1. ,  5.5, 10. ]), np.float64(4.5))

In [ ]:
np.logspace(1,20,3,base=2)

array([2.00000000e+00, 1.44815469e+03, 1.04857600e+06])

In [ ]:
x=np.arange(1,20,2)
y=np.arange(21,40,2)
x,y

(array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]),
 array([21, 23, 25, 27, 29, 31, 33, 35, 37, 39]))

In [ ]:
x.size

10

In [ ]:
y.size

10

In [ ]:
np.add(x,y)

array([22, 26, 30, 34, 38, 42, 46, 50, 54, 58])

In [ ]:
np.subtract(x,y)

array([-20, -20, -20, -20, -20, -20, -20, -20, -20, -20])

In [ ]:
np.multiply(x,y)

array([ 21,  69, 125, 189, 261, 341, 429, 525, 629, 741])

In [ ]:
np.divide(x,y)

array([0.04761905, 0.13043478, 0.2       , 0.25925926, 0.31034483,
       0.35483871, 0.39393939, 0.42857143, 0.45945946, 0.48717949])

In [ ]:
np.exp(x)

array([2.71828183e+00, 2.00855369e+01, 1.48413159e+02, 1.09663316e+03,
       8.10308393e+03, 5.98741417e+04, 4.42413392e+05, 3.26901737e+06,
       2.41549528e+07, 1.78482301e+08])

In [ ]:
np.sqrt(x)

array([1.        , 1.73205081, 2.23606798, 2.64575131, 3.        ,
       3.31662479, 3.60555128, 3.87298335, 4.12310563, 4.35889894])

In [ ]:
np.array_equal(x,y)

False

In [ ]:
x,y

(array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]),
 array([21, 23, 25, 27, 29, 31, 33, 35, 37, 39]))

In [ ]:
x==y

array([False, False, False, False, False, False, False, False, False,
       False])

In [ ]:
np.mean(x)

np.float64(10.0)

In [ ]:
np.sum(x)/10

np.float64(10.0)

In [ ]:
np.std(x)

np.float64(5.744562646538029)

In [ ]:
np.var(x)

np.float64(33.0)

In [ ]:
np.median(x)

np.float64(10.0)

In [ ]:
import random as r

In [ ]:
np.random.rand(5,6)

array([[0.90715869, 0.10593077, 0.2469748 , 0.53447392, 0.28142904,
        0.78746004],
       [0.84876761, 0.50902433, 0.16632436, 0.34674967, 0.45512121,
        0.53347472],
       [0.65651593, 0.88908142, 0.29689091, 0.4476443 , 0.11617523,
        0.15085937],
       [0.47345793, 0.27800513, 0.98444296, 0.95909768, 0.09122881,
        0.78261147],
       [0.74634582, 0.45660628, 0.68784629, 0.91964678, 0.86515738,
        0.25990438]])

In [ ]:
r.randint(1,100)

56

In [ ]:
np.random.randint(1,10,(3,3))

array([[4, 1, 5],
       [4, 1, 8],
       [5, 7, 2]])

In [ ]:
x=[i for i in range(10)]
x

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
np.random.choice(x,size=2)

array([9, 1])

In [ ]:
np.random.shuffle(x)

In [ ]:
x

[0, 3, 5, 6, 4, 2, 7, 9, 8, 1]

In [20]:
import numpy as np

In [32]:
a=np.arange(1,20,2)
b=np.arange(21,40,2)
a,b

(array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]),
 array([21, 23, 25, 27, 29, 31, 33, 35, 37, 39]))

In [33]:
c=np.copy(a)
c

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [37]:
d=a.view()

In [38]:
d

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [34]:
c[2]=1

In [35]:
c

array([ 1,  3,  1,  7,  9, 11, 13, 15, 17, 19])

In [36]:
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [39]:
d[2]=1

In [40]:
d

array([ 1,  3,  1,  7,  9, 11, 13, 15, 17, 19])

In [41]:
a

array([ 1,  3,  1,  7,  9, 11, 13, 15, 17, 19])

In [42]:
d

array([ 1,  3,  1,  7,  9, 11, 13, 15, 17, 19])

In [43]:
d.ndim

1

In [46]:
d=d.reshape(5,2)

In [47]:
d.shape

(5, 2)

In [52]:
d.sort(axis=1)

In [53]:
d

array([[ 1,  3],
       [ 1,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

In [54]:
e=np.array([1,5,7,2,4,7])
e

array([1, 5, 7, 2, 4, 7])

In [56]:
e=e.reshape(2,3)
e

array([[1, 5, 7],
       [2, 4, 7]])

In [57]:
e.shape

(2, 3)

In [58]:
e.ndim

2

In [61]:
np.sort(e,axis=0)

array([[1, 4, 7],
       [2, 5, 7]])

In [62]:
a,b

(array([ 1,  3,  1,  7,  9, 11, 13, 15, 17, 19]),
 array([21, 23, 25, 27, 29, 31, 33, 35, 37, 39]))

In [63]:
np.append(a,b)

array([ 1,  3,  1,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39])

In [64]:
np.add(a,b)

array([22, 26, 26, 34, 38, 42, 46, 50, 54, 58])

In [67]:
a=np.insert(a,2,10)

In [68]:
np.delete(a,5)

array([ 1,  3, 10,  1,  7, 11, 13, 15, 17, 19])

In [70]:
a,b

(array([ 1,  3, 10,  1,  7,  9, 11, 13, 15, 17, 19]),
 array([21, 23, 25, 27, 29, 31, 33, 35, 37, 39]))

In [75]:
a=a[:10].reshape(2,5)
b=b.reshape(2,5)
a

array([[ 1,  3, 10,  1,  7],
       [ 9, 11, 13, 15, 17]])

In [76]:
b

array([[21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39]])

In [77]:
np.concatenate((a,b),axis=1)

array([[ 1,  3, 10,  1,  7, 21, 23, 25, 27, 29],
       [ 9, 11, 13, 15, 17, 31, 33, 35, 37, 39]])

In [81]:
np.stack((a,b))

array([[[ 1,  3, 10,  1,  7],
        [ 9, 11, 13, 15, 17]],

       [[21, 23, 25, 27, 29],
        [31, 33, 35, 37, 39]]])

In [82]:
np.hstack((a,b))

array([[ 1,  3, 10,  1,  7, 21, 23, 25, 27, 29],
       [ 9, 11, 13, 15, 17, 31, 33, 35, 37, 39]])

In [83]:
np.vstack((a,b))

array([[ 1,  3, 10,  1,  7],
       [ 9, 11, 13, 15, 17],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39]])

In [88]:
a=a.reshape(-1)

In [89]:
len(a)

10

In [92]:
x,y,z,f,g=np.split(a,5)
x,y,z,f,g

(array([1, 3]),
 array([10,  1]),
 array([7, 9]),
 array([11, 13]),
 array([15, 17]))

(array([2]),)

In [94]:
a

array([ 1,  3, 10,  1,  7,  9, 11, 13, 15, 17])

In [95]:
np.where(a%2==0)

(array([2]),)

In [99]:
np.searchsorted(a,10)
s

np.int64(6)

In [98]:
a

array([ 1,  3, 10,  1,  7,  9, 11, 13, 15, 17])

In [100]:
np.sin(a)

array([ 0.84147098,  0.14112001, -0.54402111,  0.84147098,  0.6569866 ,
        0.41211849, -0.99999021,  0.42016704,  0.65028784, -0.96139749])

In [101]:
np.cos(a)

array([ 0.54030231, -0.9899925 , -0.83907153,  0.54030231,  0.75390225,
       -0.91113026,  0.0044257 ,  0.90744678, -0.75968791, -0.27516334])

In [102]:
np.log(a)

array([0.        , 1.09861229, 2.30258509, 0.        , 1.94591015,
       2.19722458, 2.39789527, 2.56494936, 2.7080502 , 2.83321334])

In [103]:
np.radians(a)

array([0.01745329, 0.05235988, 0.17453293, 0.01745329, 0.12217305,
       0.15707963, 0.19198622, 0.2268928 , 0.26179939, 0.29670597])

In [104]:
np.degrees(a)

array([ 57.29577951, 171.88733854, 572.95779513,  57.29577951,
       401.07045659, 515.66201562, 630.25357464, 744.84513367,
       859.4366927 , 974.02825172])

In [106]:
np.argmin(a)

np.int64(0)

In [107]:
np.argmax(a)

np.int64(9)

In [108]:
a

array([ 1,  3, 10,  1,  7,  9, 11, 13, 15, 17])

In [109]:
a

array([ 1,  3, 10,  1,  7,  9, 11, 13, 15, 17])

In [110]:
a.astype('float')

array([ 1.,  3., 10.,  1.,  7.,  9., 11., 13., 15., 17.])

In [113]:
len(a),len(b)

(10, 2)

In [114]:
a=np.arange(1,20,2)
b=np.arange(21,40,2)
a,b

(array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]),
 array([21, 23, 25, 27, 29, 31, 33, 35, 37, 39]))

In [116]:
np.dstack((a,b))

array([[[ 1, 21],
        [ 3, 23],
        [ 5, 25],
        [ 7, 27],
        [ 9, 29],
        [11, 31],
        [13, 33],
        [15, 35],
        [17, 37],
        [19, 39]]])