In [1]:
import numpy  as np

In [2]:
s=np.array(0,ndmin=10)
s.ndim
s

array([[[[[[[[[[0]]]]]]]]]])

In [3]:
print(np.array([1,2,3,4]).ndim)
print(np.array([[1,2,3],[4,5,6]]).ndim)
print(np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]).ndim)

1
2
3


In [4]:
s=b'gayamsunilkumar'
np.frombuffer(s,dtype='S1',offset=3,count=2)

array([b'a', b'm'], dtype='|S1')

In [5]:
a=np.array([[1,2,3],[4,5,6]])
a.ndim

2

In [6]:
for i in np.nditer(a,order='F'):
  print(i)


1
4
2
5
3
6


In [7]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
b=[i for i in range(10)]
np.fromiter(b,dtype='int',count=5)

array([0, 1, 2, 3, 4])

In [9]:
np.zeros([2,3],dtype='float')

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones([1,4])

array([[1., 1., 1., 1.]])

In [11]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
np.full([2,3],5)

array([[5, 5, 5],
       [5, 5, 5]])

In [13]:
np.arange(1,100,4,dtype='int')

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65,
       69, 73, 77, 81, 85, 89, 93, 97])

In [14]:
np.linspace(1,20,3,dtype='float',retstep=True)

(array([ 1. , 10.5, 20. ]), 9.5)

In [15]:
np.logspace(1,100,5,base=2)

array([2.00000000e+00, 5.64316032e+07, 1.59226292e+15, 4.49269746e+22,
       1.26765060e+30])

In [16]:
a.dtype

dtype('int32')

In [17]:
a.shape

(2, 3)

In [18]:
a.size

6

In [19]:
b=a.copy()
b

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
b[0][1]=8

In [22]:
b

array([[1, 8, 3],
       [4, 5, 6]])

In [23]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
s=a.view()
s

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
s[0][1]=9
s

array([[1, 9, 3],
       [4, 5, 6]])

In [27]:
a

array([[1, 9, 3],
       [4, 5, 6]])

In [28]:
a.sort(axis=0)

In [29]:
a

array([[1, 5, 3],
       [4, 9, 6]])

In [30]:
c=np.arange(1,7,).reshape(2,3)
c

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
np.append(a,c,axis=0)

array([[1, 5, 3],
       [4, 9, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [32]:
np.__version__

'1.23.5'

In [33]:
import numpy as np

In [34]:
a=np.arange(1,20,2).reshape(2,5)
b=np.arange(21,40,2).reshape(2,5)

In [35]:
a

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [36]:
b

array([[21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39]])

In [37]:
np.concatenate((a,b),axis=1)

array([[ 1,  3,  5,  7,  9, 21, 23, 25, 27, 29],
       [11, 13, 15, 17, 19, 31, 33, 35, 37, 39]])

In [38]:
np.hstack((a,b))

array([[ 1,  3,  5,  7,  9, 21, 23, 25, 27, 29],
       [11, 13, 15, 17, 19, 31, 33, 35, 37, 39]])

In [39]:
np.vstack((a,b))

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39]])

In [40]:
np.dstack((a,b))

array([[[ 1, 21],
        [ 3, 23],
        [ 5, 25],
        [ 7, 27],
        [ 9, 29]],

       [[11, 31],
        [13, 33],
        [15, 35],
        [17, 37],
        [19, 39]]])

In [41]:
a=a.flatten()

In [42]:
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [43]:
x=np.split(a,2)
c,d=x
c,d

(array([1, 3, 5, 7, 9]), array([11, 13, 15, 17, 19]))

In [44]:
np.where(a>15)

(array([8, 9], dtype=int64),)

In [45]:
np.searchsorted(a,5)

2

In [46]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


    fonttools (>=3.0<4.0) ; (python_version < "3") and extra == 'with-fonttools'
              ~~~~~~^

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [47]:
import numpy as np

In [48]:
a=np.array(10)
a

array(10)

In [49]:
a.ndim

0

In [50]:
b=np.array([1,2,23,3])
b

array([ 1,  2, 23,  3])

In [51]:
b.ndim

1

In [52]:
c=np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
c.ndim

2

In [54]:
c.shape

(2, 3)

In [55]:
c.size

6

In [56]:
c.dtype

dtype('int32')

In [57]:
type(c)

numpy.ndarray

In [58]:
d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [59]:
d.ndim

3

In [60]:
e=np.array(10,ndmin=1)
e

array([10])

In [61]:
np.__version__

'1.23.5'

In [62]:
e.ndim

1

In [63]:
b=b'gayamsunilkumar'
b

b'gayamsunilkumar'

In [64]:
np.frombuffer(b,dtype='S1')

array([b'g', b'a', b'y', b'a', b'm', b's', b'u', b'n', b'i', b'l', b'k',
       b'u', b'm', b'a', b'r'], dtype='|S1')

In [65]:
np.frombuffer(b,dtype='S1',offset=3)

array([b'a', b'm', b's', b'u', b'n', b'i', b'l', b'k', b'u', b'm', b'a',
       b'r'], dtype='|S1')

In [66]:
np.frombuffer(b,dtype='S1',offset=3,count=7)

array([b'a', b'm', b's', b'u', b'n', b'i', b'l'], dtype='|S1')

In [67]:
np.fromiter([1,2,3],dtype='float')

array([1., 2., 3.])

In [68]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
for i in np.nditer(c):
  print(i)

1
2
3
4
5
6


In [70]:
import numpy as np

In [71]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [72]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [73]:
np.full([3,4],5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [74]:
a=np.eye(3)
a.ndim

2

In [75]:
x=np.arange(1,20,2,dtype='float')
x.size

10

In [76]:
x=x[:6].reshape(2,3)
x

array([[ 1.,  3.,  5.],
       [ 7.,  9., 11.]])

In [77]:
for i in np.nditer(x,order="F"):
  print(i)

1.0
7.0
3.0
9.0
5.0
11.0


In [78]:
np.linspace(1,10,3,retstep=True)

(array([ 1. ,  5.5, 10. ]), 4.5)

In [79]:
np.logspace(1,20,3,base=2)

array([2.00000000e+00, 1.44815469e+03, 1.04857600e+06])

In [80]:
x=np.arange(1,20,2)
y=np.arange(21,40,2)
x,y

(array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]),
 array([21, 23, 25, 27, 29, 31, 33, 35, 37, 39]))

In [81]:
x.size

10

In [82]:
y.size

10

In [83]:
np.add(x,y)

array([22, 26, 30, 34, 38, 42, 46, 50, 54, 58])

In [84]:
np.subtract(x,y)

array([-20, -20, -20, -20, -20, -20, -20, -20, -20, -20])

In [85]:
np.multiply(x,y)

array([ 21,  69, 125, 189, 261, 341, 429, 525, 629, 741])

In [86]:
np.divide(x,y)

array([0.04761905, 0.13043478, 0.2       , 0.25925926, 0.31034483,
       0.35483871, 0.39393939, 0.42857143, 0.45945946, 0.48717949])

In [87]:
np.exp(x)

array([2.71828183e+00, 2.00855369e+01, 1.48413159e+02, 1.09663316e+03,
       8.10308393e+03, 5.98741417e+04, 4.42413392e+05, 3.26901737e+06,
       2.41549528e+07, 1.78482301e+08])

In [88]:
np.sqrt(x)

array([1.        , 1.73205081, 2.23606798, 2.64575131, 3.        ,
       3.31662479, 3.60555128, 3.87298335, 4.12310563, 4.35889894])

In [89]:
np.array_equal(x,y)

False

In [90]:
x,y

(array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]),
 array([21, 23, 25, 27, 29, 31, 33, 35, 37, 39]))

In [91]:
x==y

array([False, False, False, False, False, False, False, False, False,
       False])

In [92]:
np.mean(x)

10.0

In [93]:
np.sum(x)/10

10.0

In [94]:
np.std(x)

5.744562646538029

In [95]:
np.var(x)

33.0

In [96]:
np.median(x)

10.0

In [97]:
import random as r

In [98]:
np.random.rand(5,6)

array([[3.62168147e-01, 5.18061663e-02, 3.33118230e-01, 8.25796524e-02,
        7.56748906e-01, 5.63709183e-01],
       [8.13112095e-01, 9.24803154e-01, 8.33946103e-01, 5.42145163e-01,
        2.19599485e-01, 6.61606357e-01],
       [8.06546778e-02, 6.26179822e-01, 8.90631662e-01, 4.94314338e-01,
        2.41071814e-01, 6.94426822e-01],
       [4.47292873e-01, 7.70717515e-04, 2.43246938e-01, 5.18782049e-01,
        3.71201751e-02, 5.91745938e-01],
       [8.83715535e-01, 1.52328587e-01, 6.82634567e-02, 4.75493196e-01,
        2.56973564e-01, 9.12788709e-01]])

In [99]:
r.randint(1,100)

10

In [100]:
np.random.randint(1,10,(3,3))

array([[5, 6, 8],
       [7, 7, 2],
       [7, 3, 9]])

In [101]:
x=[i for i in range(10)]
x

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [102]:
np.random.choice(x,size=2)

array([2, 1])

In [103]:
np.random.shuffle(x)

In [104]:
x

[0, 8, 3, 7, 5, 9, 6, 2, 1, 4]

In [105]:
import numpy as np

In [106]:
a=np.arange(1,20,2)
b=np.arange(21,40,2)
a,b

(array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]),
 array([21, 23, 25, 27, 29, 31, 33, 35, 37, 39]))

In [107]:
c=np.copy(a)
c

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [108]:
d=a.view()

In [109]:
d

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [110]:
c[2]=1

In [111]:
c

array([ 1,  3,  1,  7,  9, 11, 13, 15, 17, 19])

In [112]:
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [113]:
d[2]=1

In [114]:
d

array([ 1,  3,  1,  7,  9, 11, 13, 15, 17, 19])

In [115]:
a

array([ 1,  3,  1,  7,  9, 11, 13, 15, 17, 19])

In [116]:
d

array([ 1,  3,  1,  7,  9, 11, 13, 15, 17, 19])

In [117]:
d.ndim

1

In [118]:
d=d.reshape(5,2)

In [119]:
d.shape

(5, 2)

In [120]:
d.sort(axis=1)

In [121]:
d

array([[ 1,  3],
       [ 1,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

In [122]:
e=np.array([1,5,7,2,4,7])
e

array([1, 5, 7, 2, 4, 7])

In [123]:
e=e.reshape(2,3)
e

array([[1, 5, 7],
       [2, 4, 7]])

In [124]:
e.shape

(2, 3)

In [125]:
e.ndim

2

In [126]:
np.sort(e,axis=0)

array([[1, 4, 7],
       [2, 5, 7]])

In [127]:
a,b

(array([ 1,  3,  1,  7,  9, 11, 13, 15, 17, 19]),
 array([21, 23, 25, 27, 29, 31, 33, 35, 37, 39]))

In [128]:
np.append(a,b)

array([ 1,  3,  1,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39])

In [129]:
np.add(a,b)

array([22, 26, 26, 34, 38, 42, 46, 50, 54, 58])

In [130]:
a=np.insert(a,2,10)

In [131]:
np.delete(a,5)

array([ 1,  3, 10,  1,  7, 11, 13, 15, 17, 19])

In [132]:
a,b

(array([ 1,  3, 10,  1,  7,  9, 11, 13, 15, 17, 19]),
 array([21, 23, 25, 27, 29, 31, 33, 35, 37, 39]))

In [133]:
a=a[:10].reshape(2,5)
b=b.reshape(2,5)
a

array([[ 1,  3, 10,  1,  7],
       [ 9, 11, 13, 15, 17]])

In [134]:
b

array([[21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39]])

In [135]:
np.concatenate((a,b),axis=1)

array([[ 1,  3, 10,  1,  7, 21, 23, 25, 27, 29],
       [ 9, 11, 13, 15, 17, 31, 33, 35, 37, 39]])

In [136]:
np.stack((a,b))

array([[[ 1,  3, 10,  1,  7],
        [ 9, 11, 13, 15, 17]],

       [[21, 23, 25, 27, 29],
        [31, 33, 35, 37, 39]]])

In [137]:
np.hstack((a,b))

array([[ 1,  3, 10,  1,  7, 21, 23, 25, 27, 29],
       [ 9, 11, 13, 15, 17, 31, 33, 35, 37, 39]])

In [138]:
np.vstack((a,b))

array([[ 1,  3, 10,  1,  7],
       [ 9, 11, 13, 15, 17],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39]])

In [139]:
a=a.reshape(-1)

In [140]:
len(a)

10

In [141]:
x,y,z,f,g=np.split(a,5)
x,y,z,f,g

(array([1, 3]),
 array([10,  1]),
 array([7, 9]),
 array([11, 13]),
 array([15, 17]))

In [142]:
a

array([ 1,  3, 10,  1,  7,  9, 11, 13, 15, 17])

In [143]:
np.where(a%2==0)

(array([2], dtype=int64),)

In [144]:
np.searchsorted(a,10)
s

array([[1, 5, 3],
       [4, 9, 6]])

In [145]:
a

array([ 1,  3, 10,  1,  7,  9, 11, 13, 15, 17])

In [146]:
np.sin(a)

array([ 0.84147098,  0.14112001, -0.54402111,  0.84147098,  0.6569866 ,
        0.41211849, -0.99999021,  0.42016704,  0.65028784, -0.96139749])

In [147]:
np.cos(a)

array([ 0.54030231, -0.9899925 , -0.83907153,  0.54030231,  0.75390225,
       -0.91113026,  0.0044257 ,  0.90744678, -0.75968791, -0.27516334])

In [148]:
np.log(a)

array([0.        , 1.09861229, 2.30258509, 0.        , 1.94591015,
       2.19722458, 2.39789527, 2.56494936, 2.7080502 , 2.83321334])

In [149]:
np.radians(a)

array([0.01745329, 0.05235988, 0.17453293, 0.01745329, 0.12217305,
       0.15707963, 0.19198622, 0.2268928 , 0.26179939, 0.29670597])

In [150]:
np.degrees(a)

array([ 57.29577951, 171.88733854, 572.95779513,  57.29577951,
       401.07045659, 515.66201562, 630.25357464, 744.84513367,
       859.4366927 , 974.02825172])

In [151]:
np.argmin(a)

0

In [152]:
np.argmax(a)

9

In [153]:
a

array([ 1,  3, 10,  1,  7,  9, 11, 13, 15, 17])

In [154]:
a

array([ 1,  3, 10,  1,  7,  9, 11, 13, 15, 17])

In [155]:
a.astype('float')

array([ 1.,  3., 10.,  1.,  7.,  9., 11., 13., 15., 17.])

In [156]:
len(a),len(b)

(10, 2)

In [157]:
a=np.arange(1,20,2)
b=np.arange(21,40,2)
a,b

(array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]),
 array([21, 23, 25, 27, 29, 31, 33, 35, 37, 39]))

In [158]:
np.dstack((a,b))

array([[[ 1, 21],
        [ 3, 23],
        [ 5, 25],
        [ 7, 27],
        [ 9, 29],
        [11, 31],
        [13, 33],
        [15, 35],
        [17, 37],
        [19, 39]]])