In [22]:
print("Hello")

Hello


15-3-25


Tuples Examples

In [29]:
x = (10,)
type(x)

tuple

In [33]:
x = (1,2,3,4)
print(x)

y=list(x) #converting to list

y.append(10)

x = tuple(y)  #converting to Tuple
print(x)

(1, 2, 3, 4)
(1, 2, 3, 4, 10)


In [34]:
x = (1,2,3,1,4,5,1)
x.count(1) #counting number of elements

3

24-03-2025


In [30]:
# Q1: Calculate the mode of the list

import statistics  # Importing the statistics module for mathematical operations

# List of temperature data
data = [34, 35, 26, 37, 2, 35]

# Calculating the mode (most frequently occurring value) from the list
mode_value = statistics.mode(data)

# Printing the mode value
print('The Mode is',mode_value)  # Expected Output: 35 (since 35 appears twice, more than any other number)


The Mode is 35


In [38]:
# Q2: Replace the last element of the list of tuples
list_of_tuples = [(10, 20, 30), (30, 40, 50), (50, 60, 70)]

new_element = (80, 90, 100)  # New tuple to replace the last element

list_of_tuples[-1] = new_element  # Replacing the last element

print("Updated list of tuples:", list_of_tuples)   # Output: [(10, 20, 30), (30, 40, 50), (80, 90, 100)]

Updated list of tuples: [(10, 20, 30), (30, 40, 50), (80, 90, 100)]


In [36]:
# 3 emp_dict = {'Name':"sridhar",'Skills':['Python','Ml','DL'],'Year':[2016,2017,2018]}   check id the emp_id is present or not

emp_dict = {'Name':"sridhar",'Skills':['Python','Ml','DL'],'Year':[2016,2017,2018]}

if emp_dict.keys == 'Emp_id':
    print("There is Emp id")
else:
    print("There is no Emp Id")

There is no Emp Id


In [37]:
# Q4: Merge two lists of tech companies into one
tech_comp1 = ['Qualcom', 'Google', 'Apple', ['Nvidia', 'Cisco', 'Samsung']]

# Flattening the nested list and merging properly
final_tech_comp = tech_comp1[:3] + tech_comp1[3]  # Extracting the first 3 elements and merging the nested list

print(final_tech_comp)  # Output: ['Qualcom', 'Google', 'Apple', 'Nvidia', 'Cisco', 'Samsung']


['Qualcom', 'Google', 'Apple', 'Nvidia', 'Cisco', 'Samsung']


In [35]:
# 5 temp = [20,30,31,22,32,39] swap the highest and lowest temp  expected output: [39,30,31,22,32,20]

# method 1
a = [20,30,31,22,32,39]
x = a.pop()
y = a.pop(0)
a.insert(0,x)
a.append(y)
print(a)

print()


# method 2
temp = [20, 30, 31, 22, 32, 39]

# Find indices of min and max values
min_index = temp.index(min(temp))
max_index = temp.index(max(temp))

# Swap the values
temp[min_index], temp[max_index] = temp[max_index], temp[min_index]

print(temp)  # Output: [39, 30, 31, 22, 32, 20]


[39, 30, 31, 22, 32, 20]

[39, 30, 31, 22, 32, 20]


In [2]:
print("testing")

testing


In [ ]:
def a():
    a=[]  # creating the empty list
    aa = int(input("Enter number of elements"))  # taking the number of elements from the user
    for i in range(aa):     # iterating the loop for the number of elements
        b = int(input(f'Enter the {i+1} element')) #
        a.append(b)
    for i in a:
        print(i/10)
        

a()


1.0
2.0


In [ ]:
def a():
    #taking the input from the user and creating the appending with the list named b
    b = list(map(int, input(f'Enter the elements').split())) 
    for i in b:
        print(f'The division of {i} with 10 is {i/10}') # dividing the list with 10 and printing the results
        
a()


The division of 10 with 10 is 1.0
The division of 20 with 10 is 2.0
The division of 30 with 10 is 3.0
The division of 40 with 10 is 4.0
The division of 50 with 10 is 5.0
The division of 60 with 10 is 6.0
The division of 70 with 10 is 7.0


In [21]:
def a(*args):
    for i in args:
        print(f'The division of {i} with 10 is {i/10}') # dividing the list with 10 and printing the results
    
    
#taking the input from the user and creating the appending with the list named 
b = tuple(map(int, input(f'Enter the elements').split()))      


26-03-2025


In [32]:
x = [i for i in range(10)] #list comprehension
print(x) #printing the list
type(x) #checking the type of the list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


list

27-03-2025

Numpy

In [1]:
import numpy as np #importing the numpy module


In [ ]:
# one dimensional array with prime numbers
prime_array = np.array([2,3,5,7,11,13]) 
print(prime_array)


[ 2  3  5  7 11 13]


In [7]:
# two dimensional array with even and odd numbers
array = np.array([[1,3,5,7,9],[2,4,6,8,10]]) 
print(array)


[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]


In [9]:
# three  dimensional array with even and odd numbers
array = np.array([[[1,3,],[2,4,]], 
                 [[7,9],[8,10]]]) 
print(array)


[[[ 1  3]
  [ 2  4]]

 [[ 7  9]
  [ 8 10]]]


In [10]:
matrix = np.random.randint(0, 2, (50,50), dtype=np.uint8) #creating the random matrix with 50 rows and 50 columns

In [11]:
print(matrix) #printing the matrix

[[0 0 0 ... 0 1 0]
 [1 1 0 ... 0 1 0]
 [1 1 0 ... 0 1 0]
 ...
 [1 0 0 ... 1 1 0]
 [0 1 0 ... 1 0 0]
 [1 0 0 ... 1 1 0]]


Array Inspection (numpy attributes)

.shape

In [ ]:
#  this returns the tuple consisting of array dimensional and can be used to resize the array

a = np.array([[1,2,3,4,5], [6,7,8,9,10]]) #creating the array with 2 rows and 5 columns
print(a.shape) #printing the shape of the array

(2, 5)


.ndim

In [15]:
# returns the number of array dimensions

a = np.array([1,2,3,4,5]) 
b = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(a.ndim)
print(b.ndim)

1
2


.size

In [ ]:
# this returns the total number of elements of an array

a = np.array([1,2,3,4,5]) #creating the array with 5 elements

b = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(a.size) #printing the size of the array

print(b.size) 

5
10


.dtype

In [ ]:
# this returns the data type of array

a = np.array(['Sridhar','Pravalli','Meghana','Hemanth','Chaitanya']) #creating the array with 5 elements

b = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(a.dtype)

print(b.dtype)

<U11
int32


.astype

In [33]:
# this changed the data type of an array

a = np.array([1,2,3,4])
print(a)
print(a.dtype)

print()

# change the data type of an array to the float 
b = a.astype('float64')
print(b)
print(b.dtype)


[1 2 3 4]
int32

[1. 2. 3. 4.]
float64


28-03-2025

Checking the Memory

In [39]:
# checking the memory in the list and in the numpy array

import numpy as np
import sys

s = [1,2,3,4,5,6,7,8,9,10] #creating the list with 10 elements
print("Size of each element of the list in bytes: ", sys.getsizeof(s)) #printing the size of the list
print("Size of the whole list in bytes: ", sys.getsizeof(s) * len(s)) #printing the size of the list


print()

a = np.array([1,2,3,4,5,6,7,8,9,10]) #creating the array with 10 elements
print("Size of each element of the NumPy array in bytes: ", a.itemsize) #printing the size of the array
print("Size of the whole NumPy array in bytes: ", a.itemsize * a.size) #printing the size of the array


Size of each element of the list in bytes:  136
Size of the whole list in bytes:  1360

Size of each element of the NumPy array in bytes:  4
Size of the whole NumPy array in bytes:  40


Performance checking (By time)

In [42]:
import numpy as np
import time

size = 1000000 #creating the size of the array

#declaring lists
list1 = range(size)
list2 = range(size)

#declaring arrays
array1 = np.arange(size)
array2 = np.arange(size)

#list time calculation
initial_time = time.time()

#multiplying the elements of the list
resultlist = [(a * b) for a, b in zip(list1, list2)] 

print("Time taken for list in seconds: ", (time.time() - initial_time)*1000,'Milliseconds') #printing the time taken for the list

#capturing the initial time for the array
initial_time = time.time()

#multiplying the elements of the array and stored in array
resultarray = array1 * array2

#printing the time taken for the array
print("Time taken for NumPy array in seconds: ", (time.time() - initial_time)*1000,'Milliseconds') 






Time taken for list in seconds:  244.354248046875 Milliseconds
Time taken for NumPy array in seconds:  20.67399024963379 Milliseconds


In [ ]:
#creating the array with 3 elements with one's
np.ones(3)

array([1., 1., 1.])

In [ ]:
#creating the array with zeros
np.zeros(3) 

array([0., 0., 0.])

In [ ]:
#creating the array with random numbers
np.random.random(3) #creating the array with random numbers

array([0.13356103, 0.71347522, 0.68150327])

Indexing and slicing

Slicing 1-D Array

In [46]:
a = np.array([1,2,3,4,5]) #creating the array with 5 elements

In [47]:
a[0] #accessing the first element of the array

1

In [48]:
a[1] #accessing the second element of the array

2

In [ ]:
a[0:2] #accessing the first two elements of the array

array([1, 2])

Slicing in 2-D Array

In [60]:
a = np.array([[1,2], [3,4],[5,6]]) #creating the array with 2 rows and 5 columns

In [61]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [62]:
a[0,1] #accessing the first row and second column element

2

In [63]:
a[1:3] #accessing the second row

array([[3, 4],
       [5, 6]])

In [70]:
a[0:2,0] #accessing the first column

array([1, 3])

In [ ]:
a[0,0] #accessing the first element

1

In [ ]:
a[1,1] #accessing the second row and second column element

4

In [74]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
a[1:3,1] 

array([4, 6])

Slicing in 3-D array

In [80]:
# for 3-D array slicing the format is array [index,rox,column]

a = np.array([[[1,2],[4,5],[5,6]],
              [[7,8],[9,10],[10,11]],
              [[12,13],[14,15],[16,17]]]) #creating the 3-D array
a

array([[[ 1,  2],
        [ 4,  5],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

In [81]:
a[0:2]

array([[[ 1,  2],
        [ 4,  5],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [10, 11]]])

In [ ]:
a[0:2,1:,1:] 

array([[[ 5],
        [ 6]],

       [[10],
        [11]]])

02-04-2024

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6])

In [ ]:
np.split(a,3)

[array([1, 2]), array([3, 4]), array([5, 6])]