In [11]:
print("Hello")

Hello


15-3-25


Tuples Examples

In [12]:
x = (10,)
type(x)

tuple

In [13]:
x = (1,2,3,4)
print(x)

y=list(x) #converting to list

y.append(10)

x = tuple(y)  #converting to Tuple
print(x)

(1, 2, 3, 4)
(1, 2, 3, 4, 10)


In [14]:
x = (1,2,3,1,4,5,1)
x.count(1) #counting number of elements

3

24-03-2025


In [15]:
# Q1: Calculate the mode of the list

import statistics  # Importing the statistics module for mathematical operations

# List of temperature data
data = [34, 35, 26, 37, 2, 35]

# Calculating the mode (most frequently occurring value) from the list
mode_value = statistics.mode(data)

# Printing the mode value
print('The Mode is',mode_value)  # Expected Output: 35 (since 35 appears twice, more than any other number)


The Mode is 35


In [16]:
# Q2: Replace the last element of the list of tuples
list_of_tuples = [(10, 20, 30), (30, 40, 50), (50, 60, 70)]

new_element = (80, 90, 100)  # New tuple to replace the last element

list_of_tuples[-1] = new_element  # Replacing the last element

print("Updated list of tuples:", list_of_tuples)   # Output: [(10, 20, 30), (30, 40, 50), (80, 90, 100)]

Updated list of tuples: [(10, 20, 30), (30, 40, 50), (80, 90, 100)]


In [17]:
# 3 emp_dict = {'Name':"sridhar",'Skills':['Python','Ml','DL'],'Year':[2016,2017,2018]}   check id the emp_id is present or not

emp_dict = {'Name':"sridhar",'Skills':['Python','Ml','DL'],'Year':[2016,2017,2018]}

if emp_dict.keys == 'Emp_id':
    print("There is Emp id")
else:
    print("There is no Emp Id")

There is no Emp Id


In [18]:
# Q4: Merge two lists of tech companies into one
tech_comp1 = ['Qualcom', 'Google', 'Apple', ['Nvidia', 'Cisco', 'Samsung']]

# Flattening the nested list and merging properly
final_tech_comp = tech_comp1[:3] + tech_comp1[3]  # Extracting the first 3 elements and merging the nested list

print(final_tech_comp)  # Output: ['Qualcom', 'Google', 'Apple', 'Nvidia', 'Cisco', 'Samsung']


['Qualcom', 'Google', 'Apple', 'Nvidia', 'Cisco', 'Samsung']


In [19]:
# 5 temp = [20,30,31,22,32,39] swap the highest and lowest temp  expected output: [39,30,31,22,32,20]

# method 1
a = [20,30,31,22,32,39]
x = a.pop()
y = a.pop(0)
a.insert(0,x)
a.append(y)
print(a)

print()


# method 2
temp = [20, 30, 31, 22, 32, 39]

# Find indices of min and max values
min_index = temp.index(min(temp))
max_index = temp.index(max(temp))

# Swap the values
temp[min_index], temp[max_index] = temp[max_index], temp[min_index]

print(temp)  # Output: [39, 30, 31, 22, 32, 20]


[39, 30, 31, 22, 32, 20]

[39, 30, 31, 22, 32, 20]


In [20]:
print("testing")

testing


In [21]:
def a():
    a=[]  # creating the empty list
    aa = int(input("Enter number of elements"))  # taking the number of elements from the user
    for i in range(aa):     # iterating the loop for the number of elements
        b = int(input(f'Enter the {i+1} element')) #
        a.append(b)
    for i in a:
        print(i/10)
        

a()


ValueError: invalid literal for int() with base 10: ''

In [ ]:
def a():
    #taking the input from the user and creating the appending with the list named b
    b = list(map(int, input(f'Enter the elements').split())) 
    for i in b:
        print(f'The division of {i} with 10 is {i/10}') # dividing the list with 10 and printing the results
        
a()


The division of 10 with 10 is 1.0
The division of 20 with 10 is 2.0
The division of 30 with 10 is 3.0
The division of 40 with 10 is 4.0
The division of 50 with 10 is 5.0
The division of 60 with 10 is 6.0
The division of 70 with 10 is 7.0


In [ ]:
def a(*args):
    for i in args:
        print(f'The division of {i} with 10 is {i/10}') # dividing the list with 10 and printing the results
    
    
#taking the input from the user and creating the appending with the list named 
b = tuple(map(int, input(f'Enter the elements').split()))      


26-03-2025


In [ ]:
x = [i for i in range(10)] #list comprehension
print(x) #printing the list
type(x) #checking the type of the list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


list

27-03-2025

Numpy

In [ ]:
import numpy as np #importing the numpy module


In [ ]:
# one dimensional array with prime numbers
prime_array = np.array([2,3,5,7,11,13]) 
print(prime_array)


[ 2  3  5  7 11 13]


In [ ]:
# two dimensional array with even and odd numbers
array = np.array([[1,3,5,7,9],[2,4,6,8,10]]) 
print(array)


[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]


In [ ]:
# three  dimensional array with even and odd numbers
array = np.array([[[1,3,],[2,4,]], 
                 [[7,9],[8,10]]]) 
print(array)


[[[ 1  3]
  [ 2  4]]

 [[ 7  9]
  [ 8 10]]]


In [ ]:
matrix = np.random.randint(0, 2, (50,50), dtype=np.uint8) #creating the random matrix with 50 rows and 50 columns

In [ ]:
print(matrix) #printing the matrix

[[0 0 0 ... 0 1 0]
 [1 1 0 ... 0 1 0]
 [1 1 0 ... 0 1 0]
 ...
 [1 0 0 ... 1 1 0]
 [0 1 0 ... 1 0 0]
 [1 0 0 ... 1 1 0]]


Array Inspection (numpy attributes)

.shape

In [ ]:
#  this returns the tuple consisting of array dimensional and can be used to resize the array

a = np.array([[1,2,3,4,5], [6,7,8,9,10]]) #creating the array with 2 rows and 5 columns
print(a.shape) #printing the shape of the array

(2, 5)


.ndim

In [ ]:
# returns the number of array dimensions

a = np.array([1,2,3,4,5]) 
b = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(a.ndim)
print(b.ndim)

1
2


.size

In [ ]:
# this returns the total number of elements of an array

a = np.array([1,2,3,4,5]) #creating the array with 5 elements

b = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(a.size) #printing the size of the array

print(b.size) 

5
10


.dtype

In [ ]:
# this returns the data type of array

a = np.array(['Sridhar','Pravalli','Meghana','Hemanth','Chaitanya']) #creating the array with 5 elements

b = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(a.dtype)

print(b.dtype)

<U11
int32


.astype

In [ ]:
# this changed the data type of an array

a = np.array([1,2,3,4])
print(a)
print(a.dtype)

print()

# change the data type of an array to the float 
b = a.astype('float64')
print(b)
print(b.dtype)


[1 2 3 4]
int32

[1. 2. 3. 4.]
float64


28-03-2025

Checking the Memory

In [ ]:
# checking the memory in the list and in the numpy array

import numpy as np
import sys

s = [1,2,3,4,5,6,7,8,9,10] #creating the list with 10 elements
print("Size of each element of the list in bytes: ", sys.getsizeof(s)) #printing the size of the list
print("Size of the whole list in bytes: ", sys.getsizeof(s) * len(s)) #printing the size of the list


print()

a = np.array([1,2,3,4,5,6,7,8,9,10]) #creating the array with 10 elements
print("Size of each element of the NumPy array in bytes: ", a.itemsize) #printing the size of the array
print("Size of the whole NumPy array in bytes: ", a.itemsize * a.size) #printing the size of the array


Size of each element of the list in bytes:  136
Size of the whole list in bytes:  1360

Size of each element of the NumPy array in bytes:  4
Size of the whole NumPy array in bytes:  40


Performance checking (By time)

In [ ]:
import numpy as np
import time

size = 1000000 #creating the size of the array

#declaring lists
list1 = range(size)
list2 = range(size)

#declaring arrays
array1 = np.arange(size)
array2 = np.arange(size)

#list time calculation
initial_time = time.time()

#multiplying the elements of the list
resultlist = [(a * b) for a, b in zip(list1, list2)] 

print("Time taken for list in seconds: ", (time.time() - initial_time)*1000,'Milliseconds') #printing the time taken for the list

#capturing the initial time for the array
initial_time = time.time()

#multiplying the elements of the array and stored in array
resultarray = array1 * array2

#printing the time taken for the array
print("Time taken for NumPy array in seconds: ", (time.time() - initial_time)*1000,'Milliseconds') 






Time taken for list in seconds:  244.354248046875 Milliseconds
Time taken for NumPy array in seconds:  20.67399024963379 Milliseconds


In [ ]:
#creating the array with 3 elements with one's
np.ones(3)

array([1., 1., 1.])

In [ ]:
#creating the array with zeros
np.zeros(3) 

array([0., 0., 0.])

In [ ]:
#creating the array with random numbers
np.random.random(3) #creating the array with random numbers

array([0.13356103, 0.71347522, 0.68150327])

Indexing and slicing

Slicing 1-D Array

In [ ]:
a = np.array([1,2,3,4,5]) #creating the array with 5 elements

In [ ]:
a[0] #accessing the first element of the array

1

In [ ]:
a[1] #accessing the second element of the array

2

In [ ]:
a[0:2] #accessing the first two elements of the array

array([1, 2])

Slicing in 2-D Array

In [ ]:
a = np.array([[1,2], [3,4],[5,6]]) #creating the array with 2 rows and 5 columns

In [ ]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
a[0,1] #accessing the first row and second column element

2

In [ ]:
a[1:3] #accessing the second row

array([[3, 4],
       [5, 6]])

In [ ]:
a[0:2,0] #accessing the first column

array([1, 3])

In [ ]:
a[0,0] #accessing the first element

1

In [ ]:
a[1,1] #accessing the second row and second column element

4

In [ ]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
a[1:3,1] 

array([4, 6])

Slicing in 3-D array

In [ ]:
# for 3-D array slicing the format is array [index,rox,column]

a = np.array([[[1,2],[4,5],[5,6]],
              [[7,8],[9,10],[10,11]],
              [[12,13],[14,15],[16,17]]]) #creating the 3-D array
a

array([[[ 1,  2],
        [ 4,  5],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

In [ ]:
a[0:2]

array([[[ 1,  2],
        [ 4,  5],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [10, 11]]])

In [ ]:
a[0:2,1:,1:] 

array([[[ 5],
        [ 6]],

       [[10],
        [11]]])

02-04-2024

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4,5,6])

In [ ]:
np.split(a,3)

[array([1, 2]), array([3, 4]), array([5, 6])]

03-04-2025

pandas

In [ ]:
import pandas as pd 

c:\Users\Nalipi Sridhar Reddy\anaconda3\lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


In [ ]:
a = pd.Series([1,2,3,4])
a

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
type(a)

pandas.core.series.Series

In [ ]:
b = [[1,2,3,4],[5,6,7,8]] #
c = pd.DataFrame(b) #
c

0  1  2  3
0  1  2  3  4
1  5  6  7  8

In [ ]:
type(c)

pandas.core.frame.DataFrame

In [9]:
a = [[1,2,3,4],[5,6,7,8]] 
pd.DataFrame(a, columns=['a','b','c','d'])

a  b  c  d
0  1  2  3  4
1  5  6  7  8

# Creating the Data Frame with dictionaries

In [1]:
# Creating the Dictionary
dct = {'ID': {0: 23, 1: 43, 2: 12, 3: 13,
              4: 67, 5: 89, 6: 90, 7: 56,
              8: 34},
       'Name': {0: 'Ram', 1: 'Deep', 2: 'Yash',
                3: 'Aman', 4: 'Arjun', 5: 'Aditya',
                6: 'Divya', 7: 'Chalsea',
                8: 'Akash' },
       'Marks': {0: 89, 1: 97, 2: 45, 3: 78,
                 4: 56, 5: 76, 6: 100, 7: 87,
                 8: 81},
       'Grade': {0: 'B', 1: 'A', 2: 'F', 3: 'C',
                 4: 'E', 5: 'C', 6: 'A', 7: 'B',
                 8: 'B'}
      }

In [2]:
# Creating the Data Frame with pandas
import pandas as pd
a = pd.DataFrame(dct)
a

c:\Users\Nalipi Sridhar Reddy\anaconda3\lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


ID     Name  Marks Grade
0  23      Ram     89     B
1  43     Deep     97     A
2  12     Yash     45     F
3  13     Aman     78     C
4  67    Arjun     56     E
5  89   Aditya     76     C
6  90    Divya    100     A
7  56  Chalsea     87     B
8  34    Akash     81     B

In [3]:
a.head() #getting the default first 5 values of the dataframe

ID   Name  Marks Grade
0  23    Ram     89     B
1  43   Deep     97     A
2  12   Yash     45     F
3  13   Aman     78     C
4  67  Arjun     56     E

In [4]:
a.head(2) #getting the  first 2 values of the dataframe

ID  Name  Marks Grade
0  23   Ram     89     B
1  43  Deep     97     A

In [5]:
a.tail() #getting the default last 5 values of the dataframe

ID     Name  Marks Grade
4  67    Arjun     56     E
5  89   Aditya     76     C
6  90    Divya    100     A
7  56  Chalsea     87     B
8  34    Akash     81     B

In [6]:
a.tail(2) #getting the last 2 values of the dataframe

ID     Name  Marks Grade
7  56  Chalsea     87     B
8  34    Akash     81     B

In [7]:
a.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   ID      9 non-null      int64 
 1   Name    9 non-null      object
 2   Marks   9 non-null      int64 
 3   Grade   9 non-null      object
dtypes: int64(2), object(2)
memory usage: 360.0+ bytes


In [8]:
a.columns 

Index(['ID', 'Name', 'Marks', 'Grade'], dtype='object')

In [9]:
a.shape # Checking the rows and columns of an dataframe

(9, 4)

In [10]:
a.size  # total number of data which are availabe in the df

36

In [11]:
a.dtypes   # to check the data types of each column

ID        int64
Name     object
Marks     int64
Grade    object
dtype: object

In [12]:
a.describe()  #only for numerical data

ID       Marks
count   9.000000    9.000000
mean   47.444444   78.777778
std    30.071212   18.123036
min    12.000000   45.000000
25%    23.000000   76.000000
50%    43.000000   81.000000
75%    67.000000   89.000000
max    90.000000  100.000000

In [13]:
a.describe(include='object') 

Name Grade
count     9     9
unique    9     5
top     Ram     B
freq      1     3

In [14]:
a['Grade'].unique()

array(['B', 'A', 'F', 'C', 'E'], dtype=object)

In [15]:
a.nunique() #display the count of unique values of particular column

ID       9
Name     9
Marks    9
Grade    5
dtype: int64

In [16]:
a['Grade'].value_counts()  # it is returns the count of the values

Grade
B    3
A    2
C    2
F    1
E    1
Name: count, dtype: int64

In [17]:
a.isnull()

ID   Name  Marks  Grade
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False  False  False
4  False  False  False  False
5  False  False  False  False
6  False  False  False  False
7  False  False  False  False
8  False  False  False  False

In [18]:
a.isnull().sum()  # returns the total null values of each column

ID       0
Name     0
Marks    0
Grade    0
dtype: int64

In [19]:
a.isnull().any()   # if there is any one null value it will return the True else if there is no null values it will print the False

ID       False
Name     False
Marks    False
Grade    False
dtype: bool

04-04-2025

In [20]:
type(a)

pandas.core.frame.DataFrame

In [21]:
a.sample(n=2)   # generates the random  data of rows and columns from the dataframe and returns

ID    Name  Marks Grade
3  13    Aman     78     C
5  89  Aditya     76     C

In [22]:
a.nlargest(3,'Marks')  # it displays the largest 3 values of the marks 

ID   Name  Marks Grade
6  90  Divya    100     A
1  43   Deep     97     A
0  23    Ram     89     B

In [23]:
a.nsmallest(3,'Marks')

ID    Name  Marks Grade
2  12    Yash     45     F
4  67   Arjun     56     E
5  89  Aditya     76     C

In [24]:
a['Marks'].mean()

78.77777777777777

In [25]:
a['Marks'].median()

81.0

In [26]:
a['Grade'].mode()

0    B
Name: Grade, dtype: object

In [27]:
a['Marks'].min()

45

In [28]:
a['Marks'].max()

100

In [29]:
a['Marks'].skew()

-0.8946188794292372

In [30]:
a['Marks'].kurt()

0.1452993590248326

In [31]:
a[['Marks','ID']].corr()

Marks        ID
Marks  1.000000  0.292645
ID     0.292645  1.000000

In [32]:
a[['Marks','ID']].cov()

Marks          ID
Marks  328.444444  159.486111
ID     159.486111  904.277778

In [33]:
a.dtypes

ID        int64
Name     object
Marks     int64
Grade    object
dtype: object

In [34]:
a.select_dtypes(include='number')

ID  Marks
0  23     89
1  43     97
2  12     45
3  13     78
4  67     56
5  89     76
6  90    100
7  56     87
8  34     81

In [35]:
a.select_dtypes(include='object')

Name Grade
0      Ram     B
1     Deep     A
2     Yash     F
3     Aman     C
4    Arjun     E
5   Aditya     C
6    Divya     A
7  Chalsea     B
8    Akash     B

In [36]:
a


ID     Name  Marks Grade
0  23      Ram     89     B
1  43     Deep     97     A
2  12     Yash     45     F
3  13     Aman     78     C
4  67    Arjun     56     E
5  89   Aditya     76     C
6  90    Divya    100     A
7  56  Chalsea     87     B
8  34    Akash     81     B

In [37]:
a.loc[0:2,['ID','Marks']] 

ID  Marks
0  23     89
1  43     97
2  12     45

In [38]:
a.iloc[0:2,1:3] 

Name  Marks
0   Ram     89
1  Deep     97

05-04-2024

In [39]:
a[a['Marks'] == 100]

ID   Name  Marks Grade
6  90  Divya    100     A

In [43]:
a[(a['Marks'] == 100) | (a['Grade'] == 'A')]

ID   Name  Marks Grade
1  43   Deep     97     A
6  90  Divya    100     A

In [51]:
a[a['Marks'].isin([100,81])]

ID   Name  Marks Grade
6  90  Divya    100     A
8  34  Akash     81     B

In [49]:
a['Marks']

0     89
1     97
2     45
3     78
4     56
5     76
6    100
7     87
8     81
Name: Marks, dtype: int64

In [50]:
a.Marks

0     89
1     97
2     45
3     78
4     56
5     76
6    100
7     87
8     81
Name: Marks, dtype: int64

In [62]:
a = a.rename(columns={'marks':'Marks','name':'Name'})  #method 1 to change the column name

In [63]:
a.rename(columns={'Marks':'marks','Name':'name'},inplace=True)

In [64]:
a.head(2)

ID  name  marks Grade
0  23   Ram     89     B
1  43  Deep     97     A

In [ ]:
a.sort_values(by='ID',ascending=False)  # sort the values in the decending order for a particular column

ID     name  marks Grade
6  90    Divya    100     A
5  89   Aditya     76     C
4  67    Arjun     56     E
7  56  Chalsea     87     B
1  43     Deep     97     A
8  34    Akash     81     B
0  23      Ram     89     B
3  13     Aman     78     C
2  12     Yash     45     F

In [ ]:
a.sort_values(by='ID')  # sort the values in the acending order for a particular column

ID     name  marks Grade
2  12     Yash     45     F
3  13     Aman     78     C
0  23      Ram     89     B
8  34    Akash     81     B
1  43     Deep     97     A
7  56  Chalsea     87     B
4  67    Arjun     56     E
5  89   Aditya     76     C
6  90    Divya    100     A

In [68]:
x = {'col1':[1,2,3,4,5],'col2':[6,7,8,9,10]}
y = {'col1':[1,2,3,4,5],'col3':[11,12,13,14,15]}

X = pd.DataFrame(x)
Y = pd.DataFrame(y)

print(X)
print(Y)


   col1  col2
0     1     6
1     2     7
2     3     8
3     4     9
4     5    10
   col1  col3
0     1    11
1     2    12
2     3    13
3     4    14
4     5    15


In [ ]:
# merging


TypeError: merge() got an unexpected keyword argument 'On'

In [72]:
pd.merge(X,Y,on='col1')

col1  col2  col3
0     1     6    11
1     2     7    12
2     3     8    13
3     4     9    14
4     5    10    15

In [73]:
a

ID     name  marks Grade
0  23      Ram     89     B
1  43     Deep     97     A
2  12     Yash     45     F
3  13     Aman     78     C
4  67    Arjun     56     E
5  89   Aditya     76     C
6  90    Divya    100     A
7  56  Chalsea     87     B
8  34    Akash     81     B

In [ ]:
a['Double Marks'] = a['marks'] * 2    # creating the new column

In [75]:
a


ID     name  marks Grade  Double Marks
0  23      Ram     89     B           178
1  43     Deep     97     A           194
2  12     Yash     45     F            90
3  13     Aman     78     C           156
4  67    Arjun     56     E           112
5  89   Aditya     76     C           152
6  90    Divya    100     A           200
7  56  Chalsea     87     B           174
8  34    Akash     81     B           162

In [76]:
a['Class'] = a['Grade'].apply(lambda x:'First' if x=='A' else 'Second')

In [77]:
a.head()

ID   name  marks Grade  Double Marks   Class
0  23    Ram     89     B           178  Second
1  43   Deep     97     A           194   First
2  12   Yash     45     F            90  Second
3  13   Aman     78     C           156  Second
4  67  Arjun     56     E           112  Second

In [83]:
a[['ID','marks']].head()

ID  marks
0  23     89
1  43     97
2  12     45
3  13     78
4  67     56

In [85]:
a.loc[:,['ID','Class']].head()

ID   Class
0  23  Second
1  43   First
2  12  Second
3  13  Second
4  67  Second

In [87]:
a.iloc[:,[0,5]].head()

ID   Class
0  23  Second
1  43   First
2  12  Second
3  13  Second
4  67  Second

In [89]:
a['marks'] = a['marks'].astype(float)
a.head(3)

ID  name  marks Grade  Double Marks   Class
0  23   Ram   89.0     B           178  Second
1  43  Deep   97.0     A           194   First
2  12  Yash   45.0     F            90  Second

In [ ]:

del a['Double Marks']


In [92]:
a.head()


ID   name  marks Grade   Class
0  23    Ram   89.0     B  Second
1  43   Deep   97.0     A   First
2  12   Yash   45.0     F  Second
3  13   Aman   78.0     C  Second
4  67  Arjun   56.0     E  Second

In [97]:
a.drop(['Class'],axis=1,inplace=True)

In [98]:
a

ID     name  marks Grade
0  23      Ram   89.0     B
1  43     Deep   97.0     A
2  12     Yash   45.0     F
3  13     Aman   78.0     C
4  67    Arjun   56.0     E
5  89   Aditya   76.0     C
6  90    Divya  100.0     A
7  56  Chalsea   87.0     B
8  34    Akash   81.0     B

In [105]:
a.drop([2],axis=1,inplace=True)

In [106]:
a

ID     name  marks Grade
0  23      Ram   89.0     B
1  43     Deep   97.0     A
2  12     Yash   45.0     F
3  13     Aman   78.0     C
4  67    Arjun   56.0     E
5  89   Aditya   76.0     C
6  90    Divya  100.0     A
7  56  Chalsea   87.0     B
8  34    Akash   81.0     B

In [ ]:
a.iloc[4,2] = 66  
a

ID     name  marks Grade
0  23      Ram   89.0     B
1  43     Deep   97.0     A
2  12     Yash   45.0     F
3  13     Aman   78.0     C
4  67    Arjun   66.0     E
5  89   Aditya   76.0     C
6  90    Divya  100.0     A
7  56  Chalsea   87.0     B
8  34    Akash   81.0     B

In [ ]:
a.replace(100,99,inplace=True) 
a

ID     name  marks Grade
0  23      Ram   89.0     B
1  43     Deep   97.0     A
2  12     Yash   45.0     F
3  13     Aman   78.0     C
4  67    Arjun   66.0     E
5  89   Aditya   76.0     C
6  90    Divya   99.0     A
7  56  Chalsea   87.0     B
8  34    Akash   81.0     B

In [109]:
import numpy as np
a.iloc[4,2] = np.nan
a

ID     name  marks Grade
0  23      Ram   89.0     B
1  43     Deep   97.0     A
2  12     Yash   45.0     F
3  13     Aman   78.0     C
4  67    Arjun    NaN     E
5  89   Aditya   76.0     C
6  90    Divya   99.0     A
7  56  Chalsea   87.0     B
8  34    Akash   81.0     B

In [111]:
a.dropna(inplace=True)

In [112]:
a

ID     name  marks Grade
0  23      Ram   89.0     B
1  43     Deep   97.0     A
2  12     Yash   45.0     F
3  13     Aman   78.0     C
5  89   Aditya   76.0     C
6  90    Divya   99.0     A
7  56  Chalsea   87.0     B
8  34    Akash   81.0     B

In [113]:
a.iloc[7,2] = np.nan
a.iloc[6,1] = np.nan

In [114]:
a

ID    name  marks Grade
0  23     Ram   89.0     B
1  43    Deep   97.0     A
2  12    Yash   45.0     F
3  13    Aman   78.0     C
5  89  Aditya   76.0     C
6  90   Divya   99.0     A
7  56     NaN   87.0     B
8  34   Akash    NaN     B

In [ ]:
a.dropna(subset=['marks'])  #subset=['Column_Name']

In [115]:
a.fillna(0,inplace=True)

In [116]:
a

ID    name  marks Grade
0  23     Ram   89.0     B
1  43    Deep   97.0     A
2  12    Yash   45.0     F
3  13    Aman   78.0     C
5  89  Aditya   76.0     C
6  90   Divya   99.0     A
7  56       0   87.0     B
8  34   Akash    0.0     B

In [117]:
a.iloc[2,2]=np.nan
a

ID    name  marks Grade
0  23     Ram   89.0     B
1  43    Deep   97.0     A
2  12    Yash    NaN     F
3  13    Aman   78.0     C
5  89  Aditya   76.0     C
6  90   Divya   99.0     A
7  56       0   87.0     B
8  34   Akash    0.0     B

In [118]:
a['marks'].mean()

75.14285714285714

In [119]:
a['marks'].fillna(a['marks'].mean(),inplace=True)

C:\Users\Nalipi Sridhar Reddy\AppData\Local\Temp\ipykernel_12688\3100635536.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  a['marks'].fillna(a['marks'].mean(),inplace=True)


In [120]:
a

ID    name      marks Grade
0  23     Ram  89.000000     B
1  43    Deep  97.000000     A
2  12    Yash  75.142857     F
3  13    Aman  78.000000     C
5  89  Aditya  76.000000     C
6  90   Divya  99.000000     A
7  56       0  87.000000     B
8  34   Akash   0.000000     B

07-04-2025