#### Python 

In [26]:
pip install numpy

    fonttools (>=3.0<4.0) ; (python_version < "3") and extra == 'with-fonttools'
              ~~~~~~^

[notice] A new release of pip is available: 24.3.1 -> 25.1
[notice] To update, run: python.exe -m pip install --upgrade pip


NumPy:

---> Installation, Importing and checking version

--->  Creating arrays ( Dimensions , from buffer, from iter , nditer)

---> Basic checks (size ,shape , dtype,type)

---> Slicing

---> Intialization with functions (zeros ,ones ,full ,eye)

---> Numerical Ranges (arange ,linspace ,logspace)

---> Functions ( Copy, Reshape , View, Sort , Append ,Insert, Delete , Concatenate , Stack , hstack, Vstack, dstack , Split, Where, Search Sorted)

---> Arithmetic Operations (Add,substract,multiply,divide,exp,sqrt,array_equal(a,b)
,a==b,min,max,std,var,sum,median,mean)

---> Random Module (randint, rand , Choice ,shuffle )

---> Universal Functions ( Unique, log , sin, cos , radians , degrees , rad2deg, argmin ,argmax , Flatten, astype, Reshape(-1)(1D))

In [27]:
import numpy as np

In [ ]:
np.version.version  #checking the version of numpy

'1.23.5'

In [ ]:
b = np.array([[4, 5, 6],
              [7, 8, 9]])
b

array([[4, 5, 6],
       [7, 8, 9]])

In [36]:
b.shape

(2, 3)

In [37]:
b.size

6

In [40]:
type(b)

numpy.ndarray

In [ ]:
b.dtype 

dtype('int32')

In [47]:
b = np.array([[4, 5, 6],
              [7, 8, 9],
              [10, 11, 12]])

In [48]:
b

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [49]:
b.shape

(3, 3)

In [50]:
b[0:2,0:2]

array([[4, 5],
       [7, 8]])

In [51]:
b[1:3,1:3]

array([[ 8,  9],
       [11, 12]])

In [56]:
b[0:2,0:]

array([[4, 5, 6],
       [7, 8, 9]])

In [63]:
b[0:1,0:1,1:2,1:2]

IndexError: too many indices for array: array is 2-dimensional, but 4 were indexed

In [66]:
i = 0
j = 0
c = b.size
for _ in c:
    print(i,j)


TypeError: 'int' object is not iterable

In [67]:
c = b.size

In [69]:
c


9

In [70]:
type(c)

int

In [84]:
aa = np.zeros((10, 10))

In [83]:
aa.shape

(3, 3)

In [80]:
aa.size

9

In [85]:
print(aa)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
b = np.array([[4, 5, 6],
              [7, 8, 9],
              [10, 11, 12]])

In [88]:
z = np.ones((3,3))

In [89]:
z

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [113]:
z = np.full((3,3), 2.5)

In [112]:
z = np.eye(3) # identity matrix

In [114]:
z

array([[2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5]])

In [115]:
print(z.dtype)

float64


In [116]:
type(z)

numpy.ndarray

In [118]:
b

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [123]:
b[0:2,0:3]

array([[4, 5, 6],
       [7, 8, 9]])